highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: https://educationnull.github.io

baseurl: /aboutme/
title: Learn Logic | About Me
name: Avinash Dubey
email: education.null@gmail.com
email_full: mailto:education.null@gmail.com
website: educationnull.github.io
website_full: https://educationnull.github.io
address: Kharghar, NaviMumbai
postcode: 410210
state: Maharastra
country: India
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
